### ISSUE TITLE
Is there any option to run the container without "--privileged"

### ISSUE THREAD

**Issue by OraclePi** [redpwn/jail#20]
the situation is that i want to deploy a pwn chall under ctfd 
 and the `--privileged` option is banned from the admin , which means in normal case i cannot run the container

**Comment by ginkoid** [comment]
Unfortunately, jail must be run with `--privileged` (or by adding Linux capabilities, but I expect those won't be allowed either).

Instead of CTFd, you can run jail with Docker on a VM from any cloud provider.

**Comment by OraclePi** [comment]
thanks
&nbsp;


OraclePi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月1日(星期四) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redpwn/jail] Is there any option to run the container without &quot;--privileged&quot; (Issue #20)





 
Unfortunately, jail must be run with --privileged (or by adding Linux capabilities, but I expect those won't be allowed either).
 
Instead of CTFd, you can run jail with Docker on a VM from any cloud provider.
