### ISSUE TITLE
1 git clone is not enough

### ISSUE THREAD

**Issue by MohamedKarrab** [redpwn/jail#22]
When I use git clone to get the repository and build a docker image, I still have to git clone the fork separately.
Please fix it, or at least add a note in the Readme.md that we need to get specifically your forked nsjail for this to work.

**Comment by ginkoid** [comment]
I recommend using the pre-built images at `pwn.red/jail` instead of building the image yourself.

**Comment by MohamedKarrab** [comment]
The image in docker hub has a vulnerability present in golang:1.20.6-bookworm, it needs to be updated

**Comment by ginkoid** [comment]
The image does not have a vulnerability. The scanner results are incorrect.
