### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by eljeffeg** [redpwn/jail#23]
Trying to host a challenge in Azure but I don't think there is a "privileged" mode like docker.  Doesn't appear to be working.  Any suggestions?

**Comment by ginkoid** [comment]
Unfortunately redpwn/jail needs to be run as privileged. What Azure service are you using to run it?

**Comment by eljeffeg** [comment]
I created a Container Registry and then pushed the image and started a Container Instance.  https://learn.microsoft.com/en-us/azure/container-instances/
