### ISSUE TITLE
Exec format Error

### ISSUE THREAD

**Issue by ladderlogix** [redpwn/jail#27]
```bash
[E][2024-08-27T01:03:37+0000][1] newProc():225 execve('/app/run') failed: Exec format error
```

I get this error when running it on a Raspberry Pi 4 with Ubuntu 24.04.

uname -a result:
```
Linux challengeInstance 6.8.0-1004-raspi #4-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 02:29:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by ginkoid** [comment]
Your Raspberry Pi is arm64 but your `/app/run` file is probably not arm64. You should compile it for arm64.

**Comment by ladderlogix** [comment]
How I tried,

```
RUN GOOS=linux GOARCH=arm64 go build -v -ldflags '-w -s' -o ./cmd/jailrun
```

in the docker and got errors with ` => ERROR [nsjail 5/5] RUN make -j `

**Comment by DarinMao** [comment]
Jail itself does not need to be recompiled. The `/app/run` file that you created needs to be compiled for arm64.

**Comment by ladderlogix** [comment]
So then what will i need to change

**Comment by DarinMao** [comment]
We don't know anything about your /app/run file, so we can't help you here.

**Comment by ladderlogix** [comment]
/app/run file is the standard one from this repo

**Comment by ladderlogix** [comment]
It is a python script

**Comment by ladderlogix** [comment]
```python
#!/usr/local/bin/python
```

Did not have the right shebang
